;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Data.Cooldown",DevComment="")
+GameplayTagList=(Tag="Data.Damage",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Dash",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Dash.Cooldown",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.LightAttack",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Shield",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Shield.Cooldown",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Buff.Shield",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Damage",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Heal",DevComment="")
+GameplayTagList=(Tag="Status.Buff.Shield",DevComment="")

